name: Beta deploy to Private Pod

on:
  repository_dispatch:
    types: [beta-private-release]
  
jobs:
  deploy_private_pod:
    name: Beta deploy to Private Pod
    runs-on: macOS-latest
    if: (startsWith(github.event.client_payload.branch_name, 'beta-release/'))
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.client_payload.branch_name }}'
    
      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Add Private Spec Repo to CocoaPods installation
        run: |
          pod repo add Rudder https://${{secrets.PALLAB_USERNAME}}:${{secrets.PALLAB_PAT}}@github.com/rudderlabs/Specs.git
        
      - name: Add Podspec to repo
        run: |
          pod repo push Rudder Rudder.podspec
