name: Deploy to Cocoapods

on:
  workflow_run:
    workflows: ['Publish new github release']
    types: ['completed']
    
jobs:
  build:
    name: Deploy to Cocoapods
    runs-on: macOS-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout source branch
      uses: actions/checkout@v4
      
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Publish to CocoaPod
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push --allow-warnings
