name: Deploy to Private Pod

on:
  pull_request:
    branches:
      - master
    types:
      - opened
  
jobs:
  deploy_private_pod:
    name: Deploy to Private Pod
    runs-on: macOS-latest
    if: (startsWith(github.event.client_payload.branch_name, 'release/') || startsWith(github.event.client_payload.branch_name, 'hotfix-release/'))
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.head.ref }}'
    
      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Add Private Spec Repo to CocoaPods installation
        run: |
          pod repo add Rudder https://${{secrets.PAT_USERNAME}}:${{secrets.PAT}}@github.com/rudderlabs/Specs.git
        
      - name: Add Podspec to repo
        run: |
          pod repo push Rudder Rudder.podspec
